# Vectorization 

Count based Vectorization 

# Bag of Words 


In [ ]:
# Create a corpus of all unique words 
# Count the Frequecy of the words in the Corpus one by one in a sentence 
# Limitation - 1) Big Sparse Vector(fill with lot of Zeros), 2) Can't Capture Semantic Meaning
import pandas as pd 
import numpy as np
data = pd.read_csv("sample_reviews.csv")
review_data = data["review_text"]


In [ ]:

# Scratch Coding 
class Bag_of_words():
    def build_vocabulary(self,texts):
        vocab = {}
        idx = 0
        for text in texts:
            for word in text.split():
                if word not in vocab:
                    vocab[word] = idx
                    idx += 1
        return vocab
    def text_to_bow_vector(self,text, vocab):
        vector = [0] * len(vocab)
        for word in text.split():
            if word in vocab:
                vector[vocab[word]] += 1 
        return vector
    def vectorize(self, review_data):
        vocab=self.build_vocabulary(texts=review_data)
        vectors = []
        for text in review_data:   
            vector=self.text_to_bow_vector(text=text, vocab=vocab)
            vectors.append(vector)
        return vectors 
    


In [51]:
# Using Python Library 
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer()
data = bow.fit_transform(review_data)
print(data.toarray())





[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


# TD-IDF = TF(Term Frequency) * IDF(Inverse Document Frequency)