# Vectorization 

Count based Vectorization 

# Bag of Words 


In [ ]:
# Create a corpus of all unique words 
# Count the Frequecy of the words in the Corpus one by one in a sentence 
# Limitation - 1) Big Sparse Vector(fill with lot of Zeros), 2) Can't Capture Semantic Meaning
import pandas as pd 
import numpy as np
import os 
data = pd.read_csv("../../sample_reviews.csv")
review_data = data["review_text"]


c:\Users\Sourav Mondal\Desktop\Practice Coding\Marketing Agent Framework\src\core


In [ ]:

# Scratch Coding 
class Bag_of_words():
    def build_vocabulary(self,texts):
        vocab = {}
        idx = 0
        for text in texts:
            for word in text.split():
                if word not in vocab:
                    vocab[word] = idx
                    idx += 1
        return vocab
    def text_to_bow_vector(self,text, vocab):
        vector = [0] * len(vocab)
        for word in text.split():
            if word in vocab:
                vector[vocab[word]] += 1 
        return vector
    def vectorize(self, review_data):
        vocab=self.build_vocabulary(texts=review_data)
        vectors = []
        for text in review_data:   
            vector=self.text_to_bow_vector(text=text, vocab=vocab)
            vectors.append(vector)
        return vectors 
    


In [ ]:
# Using Python Library 
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer()
data = bow.fit_transform(review_data)





[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


# TD-IDF = TF(Term Frequency) * IDF(Inverse Document Frequency)

In [31]:
class tf_idf():
    def fit_transform(self,review_data):
        docs = []
        for doc in review_data:
            for element in doc.lower().split():
                docs.append(element)

        vocab = []
        for item in docs:
            if item not in vocab:
                vocab.append(item)

        # Calculate TF
        # TF = count of term in document / total words in document 
        tf = []
        for sentence in review_data:
            line = sentence.lower().split()
            tf_doc = {}
            for word in vocab:
                tf_doc[word] = line.count(word) / len(line)
            tf.append(tf_doc)

        # Calculate IDF 
        # IDF = log(len(docs) + 1/ DF(t) + 1) + 1
        # DF = number of Documents containing term t 
        df = {}
        for word in vocab:
            count = 0
            for sentence in review_data:
                line = sentence.lower().split()
                if word in line:
                    count += 1
            df[word] = count  
        import math 
        idf = {}
        for word in vocab:
            idf[word] = math.log((len(review_data) + 1) / (df[word] + 1)) + 1

        # TF * IDF 
        tfidf = []
        for tf_ind in tf:
            tf_idf_doc = {}
            for word in vocab:
                tf_idf_doc[word] = tf_ind[word] * idf[word]
            tfidf.append(tf_idf_doc)
        
          

        



In [32]:
vectorizer = tf_idf()
data = vectorizer.fit_transform(review_data)

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
data = vectorizer.fit_transform(review_data)